name: alist_player
description: "依托alist的播放器、支持进度保存、历史浏览记录"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0
environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  media_kit: 1.1.11                             # Primary package.
  media_kit_video: 1.2.5                        # For video rendering.
  media_kit_libs_video: 1.0.5                   # Native video dependencies.
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  flutter_svg: ^2.0.14
  toastification: ^2.3.0
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.3.3
  flutter_breadcrumb: ^1.0.1
  postgres: ^3.4.3
  image: ^4.3.0
  timeago: ^3.7.0
  path: ^1.9.0
  flutter_staggered_animations: ^1.1.1
  names_launcher: ^0.0.1
  url_launcher: ^6.3.1
  path_provider: ^2.1.2
  flutter_local_notifications: ^17.2.4
  file_picker: ^10.1.5
  network_info_plus: ^4.1.0
  intl: ^0.19.0
  encrypt: ^5.0.3
  convert: ^3.1.1
  flutter_downloader: ^1.11.8
  permission_handler: ^11.3.1
  share_plus: ^7.2.2
  scrollable_positioned_list: ^0.3.8
  volume_controller: ^2.0.7 #音量控制
  screen_brightness: ^2.1.2 #亮度控制
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^0.4.2
  sqflite_common: ^2.5.5
  universal_io: ^2.2.2
  
dependency_overrides:
  screen_brightness: ^2.1.2
  screen_brightness_android: 2.1.2
  screen_brightness_ios: 2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_launcher_icons:
  android: true
  ios: true
  macos:
    generate: true
    image_path: "assets/icon/1024_logo.png"
  windows:
    generate: true
    image_path: "assets/icon/1024_logo.png"
    icon_size: 48
  image_path: "assets/icon/1024_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/1024_logo.png"
  remove_alpha_ios: true
names_launcher:
  name: "AlistPlayer"
  platforms:
    android:
      enable: true
      name: "AlistPlayer"
    ios:
      enable: true
      name: "AlistPlayer"
    web:
      enable: true
      name: "AlistPlayer"
    macos:
      enable: true
      name: "AlistPlayer"
    windows:
      enable: true
      name: "AlistPlayer"
    linux:
      enable: true
      name: "AlistPlayer"
